services:
    ## ############# ##
    ## EventListener ##
    ## ############# ##

    # OnManageDownloadListener
    downloadmail.listener.on_manage_download_listener.load_download_from_db:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: loadDownloadFromDb, priority: 8182 }

    downloadmail.listener.on_manage_download_listener.load_file_data:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: loadFileData, priority: 7168 }

    downloadmail.listener.on_manage_download_listener.load_form_data:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: loadFormData, priority: 6144 }

    downloadmail.listener.on_manage_download_listener.load_download_time:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: loadDownloadTime, priority: 5120 }

    downloadmail.listener.on_manage_download_listener.get_request_link:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: getRequestLink, priority: 4096 }

    downloadmail.listener.on_manage_download_listener.check_download_time:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: checkDownloadTime, priority: 3072 }

    downloadmail.listener.on_manage_download_listener.get_request_time:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: getRequestTime, priority: 2048 }

    downloadmail.listener.on_manage_download_listener.handle_download:
        class: Esit\Downloadmail\Classes\Listener\OnManageDownloadListener
        arguments: []
        tags:
            - { name: kernel.event_listener, event: on.manage.download, method: handleDownload, priority: 1024 }

    # OnManageFormListener
    downloadmail.listener.on_manage_form_listener.load_download_from_db:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: loadMailField, priority: 11264 }

    downloadmail.listener.on_manage_form_listener.gen_file_info:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: genFileInfo, priority: 10240 }

    downloadmail.listener.on_manage_form_listener.gen_download_code:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: genDownloadCode, priority: 9216 }

    downloadmail.listener.on_manage_form_listener.load_data_from_settings:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: loadDataFromSettings, priority: 8192 }

    downloadmail.listener.on_manage_form_listener.load_default_values:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: loadDefaultValues, priority: 7168 }

    downloadmail.listener.on_manage_form_listener.load_data_from_rootpage:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: loadDataFromRootpage, priority: 6144 }

    downloadmail.listener.on_manage_form_listener.load_data_from_form:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: loadDataFromForm, priority: 5120 }

    downloadmail.listener.on_manage_form_listener.set_data_for_db:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: setDataForDb, priority: 4096 }

    downloadmail.listener.on_manage_form_listener.filter_not_db_fields:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: filterNotDbFields, priority: 3072 }

    downloadmail.listener.on_manage_form_listener.save_data_in_db:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: saveDataInDb, priority: 2048 }

    downloadmail.listener.on_manage_form_listener.send_mails:
        class: Esit\Downloadmail\Classes\Listener\OnManageFormListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.manage.form, method: sendMails, priority: 1024 }

    # OnShowDownloadListener
    downloadmail.listener.on_show_download_listener.reset_download:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: resetDownload, priority: 7168 }

    downloadmail.listener.on_show_download_listener.load_data:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: loadData, priority: 6144 }

    downloadmail.listener.on_show_download_listener.convert_single_src:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: convertSingleSrc, priority: 5120 }

    downloadmail.listener.on_show_download_listener.convert_jump_to:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: convertJumpTo, priority: 4096 }

    downloadmail.listener.on_show_download_listener.convert_from_id:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: convertFromId, priority: 3072 }

    downloadmail.listener.on_show_download_listener.convert_form_data:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: convertFormData, priority: 2048 }

    downloadmail.listener.on_show_download_listener.convert_download_data:
        class: Esit\Downloadmail\Classes\Listener\OnShowDownloadListener
        arguments: ["@downloadmail.servies.helper.stringhelper"]
        tags:
            - { name: kernel.event_listener, event: on.show.download, method: convertDownloadData, priority: 1024 }
