services:
    ## ####### ##
    ## Servies ##
    ## ####### ##

    ## Helper
    downloadmail.servies.helper.blacklisthelper:
        class: Esit\Downloadmail\Classes\Services\Helper\BlacklistHelper
        public: true

    downloadmail.servies.helper.stringhelper:
        class: Esit\Downloadmail\Classes\Services\Helper\StringHelper
        public: true
